dockerimage:
	aegea-build-image-for-mission --mission-dir sra_download sra_download sra_download
image: 
	aegea-build-image-for-mission --image-type ami --mission-dir sra_download sra_download sra_download

