build_docker_image:
  base_image: ubuntu:16.04

build_image:
  rootfs_skel_dirs:
    $append: rootfs.skel
  packages:
    $extend:
      - python-scipy
      - python-redis
      - gdebi-core
  commands:
    $extend:
      - "pip install htseq==0.6.1p1"
      - "pip install redis"
      - "pip install biopython"
      - "pip install pysam"
      - "curl -L https://github.com/alexdobin/STAR/archive/2.5.2b.tar.gz | tar xz"
      - "mv STAR-2.5.2b/bin/Linux_x86_64_static/* /usr/local/bin"
      - "rm -rf STAR-2.5.2b"
      - "curl -L http://mirrors.kernel.org/ubuntu/pool/universe/r/redis/redis-tools_3.2.1-1_amd64.deb > redis-tools_3.2.1-1_amd64.deb"
      - "curl -L http://mirrors.kernel.org/ubuntu/pool/universe/r/redis/redis-server_3.2.1-1_amd64.deb > redis-server_3.2.1-1_amd64.deb"
      - "gdebi --non-interactive redis-tools_3.2.1-1_amd64.deb"
      - "gdebi --non-interactive redis-server_3.2.1-1_amd64.deb"
      - "curl -L https://sourceforge.net/projects/samtools/files/samtools/1.3/samtools-1.3.tar.bz2/download > samtools-1.3.tar.bz2"
      - " tar xjf samtools-1.3.tar.bz2; cd samtools-1.3; make; make install; samtools --version"
      - "curl -L http://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/2.8.2/sratoolkit.2.8.2-ubuntu64.tar.gz > sra_tools.tar.gz"
      - " tar xvfz sra_tools.tar.gz; cd sratoolkit.2.8.2-ubuntu64/; mv bin/* /usr/local/bin/;"

